from __future__ import annotations

import json
import os
from pathlib import Path

from app.core.semantic import ProviderError, SemanticGateway
from app.core.security import mint_context, verify_context
from app.models import Principal, Role

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "reports" / "failure-scenarios.json"
TOOL_LOG = ROOT / "logs" / "tool_calls.jsonl"


def last_tool_log_ref() -> dict | None:
    if not TOOL_LOG.exists():
        return None
    lines = TOOL_LOG.read_text(encoding="utf-8").splitlines()
    for idx in range(len(lines) - 1, -1, -1):
        try:
            row = json.loads(lines[idx])
        except json.JSONDecodeError:
            continue
        return {
            "artifact": "logs/tool_calls.jsonl",
            "line": idx + 1,
            "tool_name": row.get("tool_name"),
            "timestamp": row.get("timestamp"),
            "status": row.get("status"),
        }
    return None


def run() -> list[dict]:
    rows: list[dict] = []

    previous = os.environ.get("FORCE_GEMINI_FAILURE")
    os.environ["FORCE_GEMINI_FAILURE"] = "1"
    try:
        gateway = SemanticGateway("real")
        try:
            gateway.classify("I did not make this transaction", run_id="FAIL-FALLBACK-001")
            rows.append({
                "scenario": "gemini_primary_failure_fallback",
                "status": "handled",
                "run_id": "FAIL-FALLBACK-001",
                "provider_attempts": gateway.last_attempts,
                "root_cause": "Gemini was deliberately fault-injected for resilience verification.",
                "fix": "Classified provider failure activates the fallback provider and records provenance.",
            })
        except ProviderError as exc:
            rows.append({
                "scenario": "semantic_provider_exhaustion",
                "status": "handled",
                "run_id": "FAIL-FALLBACK-001",
                "provider_attempts": exc.attempts,
                "root_cause": "Both semantic attempts failed or were fault-injected.",
                "fix": "The workflow converts semantic exhaustion into NEEDS_INFO/human review rather than releasing a decision.",
            })
    finally:
        if previous is None:
            os.environ.pop("FORCE_GEMINI_FAILURE", None)
        else:
            os.environ["FORCE_GEMINI_FAILURE"] = previous

    from mcp_server import server

    # Mint with the SAME secret the server verifies against (ACCESS_SECRET env,
    # matching mcp_server/server.py's _ctx()). A mismatched secret would make
    # every call below fail at signature verification (ACCESS_CONTEXT_INVALID)
    # before ever reaching the customer-ownership/existence check we're trying
    # to demonstrate, collapsing both scenarios into the same false result.
    token = mint_context(
        Principal(actor_id="analyst:A-001", role=Role.analyst, team="fraud-ops"),
        "CASE-FAIL-001",
        "C-1001",
        ["txn:read"],
        os.environ.get("ACCESS_SECRET", "dev-only-change-me"),
    )
    try:
        server.get_transaction(token, "T-2001")
    except Exception as exc:
        rows.append({
            "scenario": "cross_customer_transaction_access",
            "status": "handled",
            "error": str(exc),
            "tool_log_ref": last_tool_log_ref(),
            "root_cause": "Requested transaction belongs to another synthetic customer.",
            "fix": "MCP data-plane checks signed case customer binding and returns TXN_NOT_FOUND semantics.",
        })

    try:
        server.get_transaction(token, "T-NOT-EXIST")
    except Exception as exc:
        rows.append({
            "scenario": "unknown_transaction",
            "status": "handled",
            "error": str(exc),
            "tool_log_ref": last_tool_log_ref(),
            "root_cause": "The requested synthetic transaction does not exist.",
            "fix": "Tool failure is typed and cannot become fabricated transaction data.",
        })

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps(rows, indent=2, default=str), encoding="utf-8")

    lines = [
        "# Failure Analysis",
        "",
        "This file is generated by `scripts/run_failure_scenarios.py`. Each failure is induced through an actual executable boundary and includes the corresponding provider-attempt or tool-log evidence.",
    ]
    for idx, row in enumerate(rows, 1):
        lines += [
            "",
            f"## Failure {idx}: {row['scenario']}",
            f"- Status: `{row.get('status')}`",
            f"- Run ID: `{row.get('run_id', 'n/a')}`",
            f"- Tool-log reference: `{json.dumps(row.get('tool_log_ref'), default=str)}`",
            f"- Root cause: {row.get('root_cause')}",
            f"- Fix: {row.get('fix')}",
        ]
    (ROOT / "docs/failure-analysis.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(REPORT)
    return rows


if __name__ == "__main__":
    run()
